# Generated by Django 3.0.6 on 2020-05-20 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_description',
            field=models.TextField(verbose_name='Category Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=256, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='data_added',
            field=models.DateTimeField(verbose_name='Added on'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url_link',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
